apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  ingressClassName: nginx
  rules:
    - host: demo.local
      http:
        paths:
          - path: /?(.*)   # Works well with the rewrite-target
            pathType: Prefix
            backend:
              service:
                name: django
                port:
                  number: 8000
