apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
stringData:
  SECRET_KEY: d_%_b3txmsef^7rq+qs$ots$61rdw84ppwjy=s8q@#wy7+k^#-
  DB_PASSWORD: password
  EMAIL_HOST_PASSWORD: some-password
